---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mqgiebhw/public_html/
    - cd /home/mqgiebhw/repositories/gerardo-rangel-dev
    - /opt/alt/alt-nodejs20/root/usr/bin/npm install
    - /opt/alt/alt-nodejs20/root/usr/bin/npm run build
    - /bin/cp -R dist/* $DEPLOYPATH